//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.wsLDAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLDAP.LDAPSoap")]
    public interface LDAPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsUsuarioValido", ReplyAction="*")]
        PruebaWPF.wsLDAP.EsUsuarioValidoResponse EsUsuarioValido(PruebaWPF.wsLDAP.EsUsuarioValidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsUsuarioValido", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.EsUsuarioValidoResponse> EsUsuarioValidoAsync(PruebaWPF.wsLDAP.EsUsuarioValidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersona", ReplyAction="*")]
        PruebaWPF.wsLDAP.BuscarPersonaResponse BuscarPersona(PruebaWPF.wsLDAP.BuscarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.BuscarPersonaResponse> BuscarPersonaAsync(PruebaWPF.wsLDAP.BuscarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarPassword", ReplyAction="*")]
        PruebaWPF.wsLDAP.CambiarPasswordResponse CambiarPassword(PruebaWPF.wsLDAP.CambiarPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.CambiarPasswordResponse> CambiarPasswordAsync(PruebaWPF.wsLDAP.CambiarPasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarPasswordStd", ReplyAction="*")]
        PruebaWPF.wsLDAP.RecuperarPasswordStdResponse RecuperarPasswordStd(PruebaWPF.wsLDAP.RecuperarPasswordStdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarPasswordStd", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.RecuperarPasswordStdResponse> RecuperarPasswordStdAsync(PruebaWPF.wsLDAP.RecuperarPasswordStdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsUsuarioValidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsUsuarioValido", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.EsUsuarioValidoRequestBody Body;
        
        public EsUsuarioValidoRequest() {
        }
        
        public EsUsuarioValidoRequest(PruebaWPF.wsLDAP.EsUsuarioValidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsUsuarioValidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public EsUsuarioValidoRequestBody() {
        }
        
        public EsUsuarioValidoRequestBody(string strLogin, string strPassword) {
            this.strLogin = strLogin;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsUsuarioValidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsUsuarioValidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.EsUsuarioValidoResponseBody Body;
        
        public EsUsuarioValidoResponse() {
        }
        
        public EsUsuarioValidoResponse(PruebaWPF.wsLDAP.EsUsuarioValidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsUsuarioValidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EsUsuarioValidoResult;
        
        public EsUsuarioValidoResponseBody() {
        }
        
        public EsUsuarioValidoResponseBody(bool EsUsuarioValidoResult) {
            this.EsUsuarioValidoResult = EsUsuarioValidoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersona", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.BuscarPersonaRequestBody Body;
        
        public BuscarPersonaRequest() {
        }
        
        public BuscarPersonaRequest(PruebaWPF.wsLDAP.BuscarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strLogin;
        
        public BuscarPersonaRequestBody() {
        }
        
        public BuscarPersonaRequestBody(string strNombre, string strApellido, string strLogin) {
            this.strNombre = strNombre;
            this.strApellido = strApellido;
            this.strLogin = strLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.BuscarPersonaResponseBody Body;
        
        public BuscarPersonaResponse() {
        }
        
        public BuscarPersonaResponse(PruebaWPF.wsLDAP.BuscarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement BuscarPersonaResult;
        
        public BuscarPersonaResponseBody() {
        }
        
        public BuscarPersonaResponseBody(System.Xml.Linq.XElement BuscarPersonaResult) {
            this.BuscarPersonaResult = BuscarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarPassword", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.CambiarPasswordRequestBody Body;
        
        public CambiarPasswordRequest() {
        }
        
        public CambiarPasswordRequest(PruebaWPF.wsLDAP.CambiarPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNuevoPassword;
        
        public CambiarPasswordRequestBody() {
        }
        
        public CambiarPasswordRequestBody(string strLogin, string strPassword, string strNuevoPassword) {
            this.strLogin = strLogin;
            this.strPassword = strPassword;
            this.strNuevoPassword = strNuevoPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.CambiarPasswordResponseBody Body;
        
        public CambiarPasswordResponse() {
        }
        
        public CambiarPasswordResponse(PruebaWPF.wsLDAP.CambiarPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CambiarPasswordResult;
        
        public CambiarPasswordResponseBody() {
        }
        
        public CambiarPasswordResponseBody(bool CambiarPasswordResult) {
            this.CambiarPasswordResult = CambiarPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarPasswordStdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarPasswordStd", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.RecuperarPasswordStdRequestBody Body;
        
        public RecuperarPasswordStdRequest() {
        }
        
        public RecuperarPasswordStdRequest(PruebaWPF.wsLDAP.RecuperarPasswordStdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperarPasswordStdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLogin;
        
        public RecuperarPasswordStdRequestBody() {
        }
        
        public RecuperarPasswordStdRequestBody(string strLogin) {
            this.strLogin = strLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperarPasswordStdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperarPasswordStdResponse", Namespace="http://tempuri.org/", Order=0)]
        public PruebaWPF.wsLDAP.RecuperarPasswordStdResponseBody Body;
        
        public RecuperarPasswordStdResponse() {
        }
        
        public RecuperarPasswordStdResponse(PruebaWPF.wsLDAP.RecuperarPasswordStdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperarPasswordStdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecuperarPasswordStdResult;
        
        public RecuperarPasswordStdResponseBody() {
        }
        
        public RecuperarPasswordStdResponseBody(string RecuperarPasswordStdResult) {
            this.RecuperarPasswordStdResult = RecuperarPasswordStdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LDAPSoapChannel : PruebaWPF.wsLDAP.LDAPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LDAPSoapClient : System.ServiceModel.ClientBase<PruebaWPF.wsLDAP.LDAPSoap>, PruebaWPF.wsLDAP.LDAPSoap {
        
        public LDAPSoapClient() {
        }
        
        public LDAPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LDAPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDAPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDAPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWPF.wsLDAP.EsUsuarioValidoResponse PruebaWPF.wsLDAP.LDAPSoap.EsUsuarioValido(PruebaWPF.wsLDAP.EsUsuarioValidoRequest request) {
            return base.Channel.EsUsuarioValido(request);
        }
        
        public bool EsUsuarioValido(string strLogin, string strPassword) {
            PruebaWPF.wsLDAP.EsUsuarioValidoRequest inValue = new PruebaWPF.wsLDAP.EsUsuarioValidoRequest();
            inValue.Body = new PruebaWPF.wsLDAP.EsUsuarioValidoRequestBody();
            inValue.Body.strLogin = strLogin;
            inValue.Body.strPassword = strPassword;
            PruebaWPF.wsLDAP.EsUsuarioValidoResponse retVal = ((PruebaWPF.wsLDAP.LDAPSoap)(this)).EsUsuarioValido(inValue);
            return retVal.Body.EsUsuarioValidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.EsUsuarioValidoResponse> PruebaWPF.wsLDAP.LDAPSoap.EsUsuarioValidoAsync(PruebaWPF.wsLDAP.EsUsuarioValidoRequest request) {
            return base.Channel.EsUsuarioValidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWPF.wsLDAP.EsUsuarioValidoResponse> EsUsuarioValidoAsync(string strLogin, string strPassword) {
            PruebaWPF.wsLDAP.EsUsuarioValidoRequest inValue = new PruebaWPF.wsLDAP.EsUsuarioValidoRequest();
            inValue.Body = new PruebaWPF.wsLDAP.EsUsuarioValidoRequestBody();
            inValue.Body.strLogin = strLogin;
            inValue.Body.strPassword = strPassword;
            return ((PruebaWPF.wsLDAP.LDAPSoap)(this)).EsUsuarioValidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWPF.wsLDAP.BuscarPersonaResponse PruebaWPF.wsLDAP.LDAPSoap.BuscarPersona(PruebaWPF.wsLDAP.BuscarPersonaRequest request) {
            return base.Channel.BuscarPersona(request);
        }
        
        public System.Xml.Linq.XElement BuscarPersona(string strNombre, string strApellido, string strLogin) {
            PruebaWPF.wsLDAP.BuscarPersonaRequest inValue = new PruebaWPF.wsLDAP.BuscarPersonaRequest();
            inValue.Body = new PruebaWPF.wsLDAP.BuscarPersonaRequestBody();
            inValue.Body.strNombre = strNombre;
            inValue.Body.strApellido = strApellido;
            inValue.Body.strLogin = strLogin;
            PruebaWPF.wsLDAP.BuscarPersonaResponse retVal = ((PruebaWPF.wsLDAP.LDAPSoap)(this)).BuscarPersona(inValue);
            return retVal.Body.BuscarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.BuscarPersonaResponse> PruebaWPF.wsLDAP.LDAPSoap.BuscarPersonaAsync(PruebaWPF.wsLDAP.BuscarPersonaRequest request) {
            return base.Channel.BuscarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWPF.wsLDAP.BuscarPersonaResponse> BuscarPersonaAsync(string strNombre, string strApellido, string strLogin) {
            PruebaWPF.wsLDAP.BuscarPersonaRequest inValue = new PruebaWPF.wsLDAP.BuscarPersonaRequest();
            inValue.Body = new PruebaWPF.wsLDAP.BuscarPersonaRequestBody();
            inValue.Body.strNombre = strNombre;
            inValue.Body.strApellido = strApellido;
            inValue.Body.strLogin = strLogin;
            return ((PruebaWPF.wsLDAP.LDAPSoap)(this)).BuscarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWPF.wsLDAP.CambiarPasswordResponse PruebaWPF.wsLDAP.LDAPSoap.CambiarPassword(PruebaWPF.wsLDAP.CambiarPasswordRequest request) {
            return base.Channel.CambiarPassword(request);
        }
        
        public bool CambiarPassword(string strLogin, string strPassword, string strNuevoPassword) {
            PruebaWPF.wsLDAP.CambiarPasswordRequest inValue = new PruebaWPF.wsLDAP.CambiarPasswordRequest();
            inValue.Body = new PruebaWPF.wsLDAP.CambiarPasswordRequestBody();
            inValue.Body.strLogin = strLogin;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strNuevoPassword = strNuevoPassword;
            PruebaWPF.wsLDAP.CambiarPasswordResponse retVal = ((PruebaWPF.wsLDAP.LDAPSoap)(this)).CambiarPassword(inValue);
            return retVal.Body.CambiarPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.CambiarPasswordResponse> PruebaWPF.wsLDAP.LDAPSoap.CambiarPasswordAsync(PruebaWPF.wsLDAP.CambiarPasswordRequest request) {
            return base.Channel.CambiarPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWPF.wsLDAP.CambiarPasswordResponse> CambiarPasswordAsync(string strLogin, string strPassword, string strNuevoPassword) {
            PruebaWPF.wsLDAP.CambiarPasswordRequest inValue = new PruebaWPF.wsLDAP.CambiarPasswordRequest();
            inValue.Body = new PruebaWPF.wsLDAP.CambiarPasswordRequestBody();
            inValue.Body.strLogin = strLogin;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strNuevoPassword = strNuevoPassword;
            return ((PruebaWPF.wsLDAP.LDAPSoap)(this)).CambiarPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWPF.wsLDAP.RecuperarPasswordStdResponse PruebaWPF.wsLDAP.LDAPSoap.RecuperarPasswordStd(PruebaWPF.wsLDAP.RecuperarPasswordStdRequest request) {
            return base.Channel.RecuperarPasswordStd(request);
        }
        
        public string RecuperarPasswordStd(string strLogin) {
            PruebaWPF.wsLDAP.RecuperarPasswordStdRequest inValue = new PruebaWPF.wsLDAP.RecuperarPasswordStdRequest();
            inValue.Body = new PruebaWPF.wsLDAP.RecuperarPasswordStdRequestBody();
            inValue.Body.strLogin = strLogin;
            PruebaWPF.wsLDAP.RecuperarPasswordStdResponse retVal = ((PruebaWPF.wsLDAP.LDAPSoap)(this)).RecuperarPasswordStd(inValue);
            return retVal.Body.RecuperarPasswordStdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWPF.wsLDAP.RecuperarPasswordStdResponse> PruebaWPF.wsLDAP.LDAPSoap.RecuperarPasswordStdAsync(PruebaWPF.wsLDAP.RecuperarPasswordStdRequest request) {
            return base.Channel.RecuperarPasswordStdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWPF.wsLDAP.RecuperarPasswordStdResponse> RecuperarPasswordStdAsync(string strLogin) {
            PruebaWPF.wsLDAP.RecuperarPasswordStdRequest inValue = new PruebaWPF.wsLDAP.RecuperarPasswordStdRequest();
            inValue.Body = new PruebaWPF.wsLDAP.RecuperarPasswordStdRequestBody();
            inValue.Body.strLogin = strLogin;
            return ((PruebaWPF.wsLDAP.LDAPSoap)(this)).RecuperarPasswordStdAsync(inValue);
        }
    }
}
