//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.wsOffice365 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uni.edu.ni/", ConfigurationName="wsOffice365.authSoap")]
    public interface authSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UserName del espacio de nombres http://uni.edu.ni/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://uni.edu.ni/Validate", ReplyAction="*")]
        PruebaWPF.wsOffice365.ValidateResponse Validate(PruebaWPF.wsOffice365.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uni.edu.ni/Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaWPF.wsOffice365.ValidateResponse> ValidateAsync(PruebaWPF.wsOffice365.ValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://uni.edu.ni/", Order=0)]
        public PruebaWPF.wsOffice365.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(PruebaWPF.wsOffice365.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uni.edu.ni/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://uni.edu.ni/", Order=0)]
        public PruebaWPF.wsOffice365.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(PruebaWPF.wsOffice365.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://uni.edu.ni/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(bool ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface authSoapChannel : PruebaWPF.wsOffice365.authSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authSoapClient : System.ServiceModel.ClientBase<PruebaWPF.wsOffice365.authSoap>, PruebaWPF.wsOffice365.authSoap {
        
        public authSoapClient() {
        }
        
        public authSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public authSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaWPF.wsOffice365.ValidateResponse PruebaWPF.wsOffice365.authSoap.Validate(PruebaWPF.wsOffice365.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public bool Validate(string UserName, string Password) {
            PruebaWPF.wsOffice365.ValidateRequest inValue = new PruebaWPF.wsOffice365.ValidateRequest();
            inValue.Body = new PruebaWPF.wsOffice365.ValidateRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            PruebaWPF.wsOffice365.ValidateResponse retVal = ((PruebaWPF.wsOffice365.authSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaWPF.wsOffice365.ValidateResponse> PruebaWPF.wsOffice365.authSoap.ValidateAsync(PruebaWPF.wsOffice365.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaWPF.wsOffice365.ValidateResponse> ValidateAsync(string UserName, string Password) {
            PruebaWPF.wsOffice365.ValidateRequest inValue = new PruebaWPF.wsOffice365.ValidateRequest();
            inValue.Body = new PruebaWPF.wsOffice365.ValidateRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((PruebaWPF.wsOffice365.authSoap)(this)).ValidateAsync(inValue);
        }
    }
}
