//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenteExternoCat
    {
        public int IdAgenteExterno { get; set; }
        public string Nombre { get; set; }
        public int IdIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public string Procedencia { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual IdentificacionAgenteExterno IdentificacionAgenteExterno { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
