//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnulacionPago
    {
        public int IdAnulacionPago { get; set; }
        public int IdPago { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
