//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArancelTipoDeposito
    {
        public int IdArancelTipoDeposito { get; set; }
        public int IdArancel { get; set; }
        public int IdTipoDeposito { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Arancel Arancel { get; set; }
        public virtual TipoDeposito TipoDeposito { get; set; }
    }
}
