//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoNoEfectivo
    {
        public int IdArqueoNoEfectivo { get; set; }
        public int IdArqueo { get; set; }
        public int IdFormaPago { get; set; }
        public int IdReciboPago { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
