//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoRecibo
    {
        public int IdArqueoRecibo { get; set; }
        public int IdArqueo { get; set; }
        public int IdRecibo { get; set; }
        public string Serie { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Recibo1 Recibo1 { get; set; }
        public virtual Arqueo Arqueo { get; set; }
    }
}
