//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASD
    {
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> SaldoInicial { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public byte IdActividad { get; set; }
        public string NombreActividad { get; set; }
        public string CuentaSuperior { get; set; }
        public string Superior { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Mes { get; set; }
    }
}
