//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco_DisponibilidadFondo
    {
        public int IdPeriodoGeneral { get; set; }
        public int IdPeriodoEspecifico { get; set; }
        public int IdActividad { get; set; }
        public byte IdFuenteFinanciamiento { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Reserva { get; set; }
        public Nullable<byte> IdMoneda { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    }
}
