//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco_PeriodoEspecifico
    {
        public int IdPeriodoGeneral { get; set; }
        public int IdPeriodoEspecifico { get; set; }
        public Nullable<int> IdPeriodoContable { get; set; }
        public Nullable<System.DateTime> FechaInicia { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    }
}
