//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrera()
        {
            this.EstudianteCarrera = new HashSet<EstudianteCarrera>();
        }
    
        public string IdCarrera { get; set; }
        public string IdFacultad { get; set; }
        public byte IdTipoCarrera { get; set; }
        public string Nombre { get; set; }
        public byte Estado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual CarreraTipo CarreraTipo { get; set; }
        public virtual Facultad Facultad { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteCarrera> EstudianteCarrera { get; set; }
    }
}
