//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangePassword
    {
        public int ID { get; set; }
        public string GoalUser { get; set; }
        public string UserChange { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hostname { get; set; }
        public string IPHost { get; set; }
        public Nullable<bool> Success { get; set; }
    }
}
