//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteCierre
    {
        public int IdComprobanteCierre { get; set; }
        public byte IdPeriodoGeneral { get; set; }
        public byte IdPrograma { get; set; }
        public int IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    }
}
