//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteDiario()
        {
            this.DocumentoEnlace = new HashSet<DocumentoEnlace>();
            this.LineaComprobanteDiario = new HashSet<LineaComprobanteDiario>();
        }
    
        public int IdComprobanteDiario { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public byte IdPrograma { get; set; }
        public Nullable<int> IdImpresion { get; set; }
        public byte IdTipoComprobante { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string Concepto { get; set; }
        public byte Estado { get; set; }
        public Nullable<byte> IdFuenteFinanciamiento { get; set; }
        public Nullable<int> ChequeAsociado { get; set; }
        public string LoginCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string LoginImpresion { get; set; }
        public Nullable<bool> IndModulo { get; set; }
        public bool RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoEnlace> DocumentoEnlace { get; set; }
        public virtual PeriodoEspecifico PeriodoEspecifico { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual TipoComprobante TipoComprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaComprobanteDiario> LineaComprobanteDiario { get; set; }
    }
}
