//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacionBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConciliacionBanco()
        {
            this.ConciliacionBancoDetalle = new HashSet<ConciliacionBancoDetalle>();
        }
    
        public short IdConciliacionBanco { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public short IdCuentaContable { get; set; }
        public byte TipoMoneda { get; set; }
        public byte Estado { get; set; }
        public decimal SaldoLibroCordoba { get; set; }
        public Nullable<decimal> SaldoLibroDolar { get; set; }
        public decimal SaldoBancoCordoba { get; set; }
        public Nullable<decimal> SaldoBancoDolar { get; set; }
        public string Observacion { get; set; }
        public string LoginCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte RegAnulado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual PeriodoEspecifico PeriodoEspecifico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConciliacionBancoDetalle> ConciliacionBancoDetalle { get; set; }
    }
}
