//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DetalleMovimientoIngreso = new HashSet<DetalleMovimientoIngreso>();
            this.Arancel = new HashSet<Arancel>();
        }
    
        public short IdCuentaContable { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<byte> IdOrdenGrupo { get; set; }
        public Nullable<byte> IdTipoCuenta { get; set; }
        public string CuentaSuperior { get; set; }
        public Nullable<int> CuentaGrupo { get; set; }
        public string CuentaContable1 { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public bool Tipo { get; set; }
        public bool BalanceResultado { get; set; }
        public bool Acumulativa { get; set; }
        public string Instructivo { get; set; }
        public string InstructivoDebito { get; set; }
        public string InstructivoCredito { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimientoIngreso> DetalleMovimientoIngreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arancel> Arancel { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
    }
}
