//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DetalleMovimientoIngreso = new HashSet<DetalleMovimientoIngreso>();
            this.BalanzaComprobacion = new HashSet<BalanzaComprobacion>();
            this.ConceptoDetalle = new HashSet<ConceptoDetalle>();
            this.ConciliacionBanco = new HashSet<ConciliacionBanco>();
            this.CuentaAuxiliar = new HashSet<CuentaAuxiliar>();
            this.Arancel = new HashSet<Arancel>();
            this.EjecucionPresupuestaria = new HashSet<EjecucionPresupuestaria>();
            this.Empleado = new HashSet<Empleado>();
            this.EPLineaComprobanteDiario = new HashSet<EPLineaComprobanteDiario>();
            this.EPLineaComprobantePago = new HashSet<EPLineaComprobantePago>();
            this.EstructuraCuenta = new HashSet<EstructuraCuenta>();
            this.LineaComprobanteDiario = new HashSet<LineaComprobanteDiario>();
            this.LineaComprobantePago = new HashSet<LineaComprobantePago>();
            this.Proveedor = new HashSet<Proveedor>();
            this.ReciboDetalle = new HashSet<ReciboDetalle>();
            this.SolicitudCheque = new HashSet<SolicitudCheque>();
        }
    
        public short IdCuentaContable { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<byte> IdOrdenGrupo { get; set; }
        public Nullable<byte> IdTipoCuenta { get; set; }
        public string CuentaSuperior { get; set; }
        public Nullable<int> CuentaGrupo { get; set; }
        public string CuentaContable1 { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public bool Tipo { get; set; }
        public bool BalanceResultado { get; set; }
        public bool Acumulativa { get; set; }
        public string Instructivo { get; set; }
        public string InstructivoDebito { get; set; }
        public string InstructivoCredito { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimientoIngreso> DetalleMovimientoIngreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalanzaComprobacion> BalanzaComprobacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConceptoDetalle> ConceptoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConciliacionBanco> ConciliacionBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaAuxiliar> CuentaAuxiliar { get; set; }
        public virtual CuentaBanco CuentaBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arancel> Arancel { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EjecucionPresupuestaria> EjecucionPresupuestaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPLineaComprobanteDiario> EPLineaComprobanteDiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPLineaComprobantePago> EPLineaComprobantePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstructuraCuenta> EstructuraCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaComprobanteDiario> LineaComprobanteDiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaComprobantePago> LineaComprobantePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboDetalle> ReciboDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCheque> SolicitudCheque { get; set; }
    }
}
