//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMovimientoIngreso
    {
        public int IdDetalleMovimientoIngreso { get; set; }
        public int IdMovimientoIngreso { get; set; }
        public short IdCuentaContable { get; set; }
        public bool Naturaleza { get; set; }
        public decimal FactorPorcentual { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual MovimientoIngreso MovimientoIngreso { get; set; }
    }
}
