//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOrdenPagoArancel
    {
        public int IdDetalleOrdenPago { get; set; }
        public int IdOrdenPago { get; set; }
        public int IdPrecioArancel { get; set; }
        public string Concepto { get; set; }
        public decimal PrecioVariable { get; set; }
        public Nullable<int> IdExoneracion { get; set; }
        public decimal Descuento { get; set; }
        public string IdAreaIngreso { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ArancelPrecio ArancelPrecio { get; set; }
        public virtual Exoneracion Exoneracion { get; set; }
        public virtual OrdenPago OrdenPago { get; set; }
    }
}
