//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoEnlace
    {
        public int Secuencia { get; set; }
        public Nullable<int> IdCP { get; set; }
        public Nullable<int> IdCD { get; set; }
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<byte> RegAnulado { get; set; }
    
        public virtual ComprobanteDiario ComprobanteDiario { get; set; }
        public virtual ComprobantePago ComprobantePago { get; set; }
        public virtual SolicitudCheque SolicitudCheque { get; set; }
    }
}
