//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EjecucionPresupuestaria
    {
        public short IdCuentaContable { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public byte IdPrograma { get; set; }
        public byte IdProyecto { get; set; }
        public byte IdActividad { get; set; }
        public decimal DebeInicial { get; set; }
        public decimal HaberInicial { get; set; }
        public decimal DebeMes { get; set; }
        public decimal HaberMes { get; set; }
        public decimal DebeFinal { get; set; }
        public decimal HaberFinal { get; set; }
        public string LoginCreacion { get; set; }
        public byte RegAnulado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual PeriodoEspecifico PeriodoEspecifico { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
