//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPComprobantePago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPComprobantePago()
        {
            this.EPLineaComprobantePago = new HashSet<EPLineaComprobantePago>();
        }
    
        public int IdComprobantePago { get; set; }
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public byte IdPrograma { get; set; }
        public int IdImpresion { get; set; }
        public Nullable<System.DateTime> FechaImpresionCK { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Estado { get; set; }
        public bool Extension { get; set; }
        public string LoginCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string LoginImpresion { get; set; }
        public Nullable<bool> IndModulo { get; set; }
        public bool RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPLineaComprobantePago> EPLineaComprobantePago { get; set; }
    }
}
