//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstructuraCuenta
    {
        public byte IdActividad { get; set; }
        public short IdCuentaContable { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
