//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteCarrera
    {
        public string EstudianteCarne { get; set; }
        public string IdCarrera { get; set; }
        public string IdFacultad { get; set; }
        public byte EstCarEstado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
