//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exoneracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exoneracion()
        {
            this.DetOrdenPagoArancel = new HashSet<DetOrdenPagoArancel>();
        }
    
        public int IdExoneracion { get; set; }
        public string Identificador { get; set; }
        public int IdTipoDeposito { get; set; }
        public int IdArancel { get; set; }
        public decimal Exonerado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public bool regAnulado { get; set; }
        public string Autorizadopor { get; set; }
        public int IdArancelPrecio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Arancel Arancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetOrdenPagoArancel> DetOrdenPagoArancel { get; set; }
        public virtual TipoDeposito TipoDeposito { get; set; }
        public virtual ArancelPrecio ArancelPrecio { get; set; }
    }
}
