//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.PerfilContenido = new HashSet<PerfilContenido>();
        }
    
        public int IDMenu { get; set; }
        public int NoItem { get; set; }
        public int NoFuncion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> Comando { get; set; }
        public string Argumento { get; set; }
        public Nullable<int> AyudaNum { get; set; }
        public byte Tipo { get; set; }
        public string Contabilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilContenido> PerfilContenido { get; set; }
    }
}
