//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoIngreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoIngreso()
        {
            this.DetalleMovimientoIngreso = new HashSet<DetalleMovimientoIngreso>();
        }
    
        public int IdMovimientoIngreso { get; set; }
        public int IdFormaPago { get; set; }
        public int IdMoneda { get; set; }
        public int IdRecinto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimientoIngreso> DetalleMovimientoIngreso { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
