//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroSistema
    {
        public Nullable<byte> IdRecinto { get; set; }
        public int IdReciboImpresoInicial { get; set; }
        public int IdReciboImpresoFinal { get; set; }
        public string SerieRecibo { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<System.DateTime> FechaVariacionCambiaria { get; set; }
        public byte CodigoPaisNicaragua { get; set; }
        public string LoginRecibo { get; set; }
        public int IdChequeInicial { get; set; }
        public int IdChequeFinal { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public string AnnoVigente { get; set; }
        public string LoginDirector { get; set; }
        public string LoginAdmon { get; set; }
        public bool RegAnulado { get; set; }
    }
}
