//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroContraloria
    {
        public int Secuencia { get; set; }
        public Nullable<int> PI { get; set; }
        public Nullable<int> PF { get; set; }
        public string Usuario { get; set; }
        public string Net_Address { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    }
}
