//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdPermiso { get; set; }
        public byte IdPerfil { get; set; }
        public int IdPantalla { get; set; }
        public byte IdRecinto { get; set; }
        public int IdPermisoName { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Pantalla Pantalla { get; set; }
        public virtual PermisoName PermisoName { get; set; }
    }
}
