//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
            this.Docentes = new HashSet<Docentes>();
            this.Empleado = new HashSet<Empleado>();
            this.Estudiantes = new HashSet<Estudiantes>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public int PersonaCodigo { get; set; }
        public string PersonaCedula { get; set; }
        public string PersonaINSS { get; set; }
        public string PersonaNombre1 { get; set; }
        public string PersonaNombre2 { get; set; }
        public string PersonaApellido1 { get; set; }
        public string PersonaApellido2 { get; set; }
        public bool PersonaSexo { get; set; }
        public byte PersonaEstadoCivil { get; set; }
        public Nullable<System.DateTime> PersonaFechaNac { get; set; }
        public Nullable<bool> PersonaNacioNic { get; set; }
        public Nullable<short> MunicipioCodNac { get; set; }
        public Nullable<short> PaisCodigoNac { get; set; }
        public string PersonaDireccion { get; set; }
        public string PersonaDireccionPostal { get; set; }
        public Nullable<short> MunicipioCodHab { get; set; }
        public string PersonaTelefono1 { get; set; }
        public string PersonaTelefono2 { get; set; }
        public string PersonaCelular { get; set; }
        public string PersonaEMail { get; set; }
        public string PersonaWebSite { get; set; }
        public string PersonaCenTrab { get; set; }
        public string PersonaCenTrabCargo { get; set; }
        public string PersonaCenTrabTel { get; set; }
        public string PersonaCenTrabExt { get; set; }
        public string PersonaCenTrabFax { get; set; }
        public Nullable<int> PersonaCodigoMadre { get; set; }
        public Nullable<int> PersonaCodigoPadre { get; set; }
        public Nullable<int> PersonaCodigoContEmer { get; set; }
        public byte[] PersonaFoto { get; set; }
        public string LoginCreacion { get; set; }
        public byte RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docentes> Docentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
