//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoEstado
    {
        public int IdPrestamo { get; set; }
        public byte IdEstadoPrestamo { get; set; }
        public Nullable<byte> IdEstado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    
        public virtual PrestamoDocumento PrestamoDocumento { get; set; }
    }
}
