//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int IdPresupuesto { get; set; }
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public Nullable<byte> IdPrograma { get; set; }
        public Nullable<byte> IdPeriodoEspecifico { get; set; }
        public string Codificacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool RendicionFactura { get; set; }
        public bool RendicionRecibo { get; set; }
        public bool RendicionContrato { get; set; }
        public bool RendicionPagare { get; set; }
        public bool RendicionCuenta { get; set; }
        public bool RendicionFiniquito { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual PeriodoEspecifico PeriodoEspecifico { get; set; }
        public virtual Programa Programa { get; set; }
    }
}
