//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Beneficiario = new HashSet<Beneficiario>();
        }
    
        public int IdProveedor { get; set; }
        public Nullable<int> PersonaCodigo { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<byte> IdMunicipio { get; set; }
        public string NombreComercial { get; set; }
        public string Proveedor1 { get; set; }
        public string RUC { get; set; }
        public string Cedula { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SitioWeb { get; set; }
        public decimal Saldo { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
