//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_RendicionesPendientes
    {
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public Nullable<byte> IdActividad { get; set; }
        public string Actividad { get; set; }
        public int IdBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<byte> IdPeriodoEspecifico { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaEntregado { get; set; }
        public Nullable<byte> TipoMoneda { get; set; }
        public string Moneda { get; set; }
        public decimal TasaCambio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Concepto { get; set; }
        public Nullable<byte> IdFuente { get; set; }
        public string Fuente { get; set; }
        public Nullable<short> IdCuentaBanco { get; set; }
        public string CuentaBanco { get; set; }
        public int IdComprobantePago { get; set; }
        public int IdImpresion { get; set; }
        public string LoginCreacion { get; set; }
        public string LoginImpresion { get; set; }
        public Nullable<short> IdCuentaLinea { get; set; }
        public string CuentaContable { get; set; }
        public string CuentaLinea { get; set; }
        public Nullable<decimal> Debe { get; set; }
    }
}
