//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_ComprobantesaRendir
    {
        public string Interno { get; set; }
        public string IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public string Concepto { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public int Interno_Ck { get; set; }
        public int Cheque { get; set; }
        public int IdSolicitud { get; set; }
        public int Año_Ck { get; set; }
        public int Vinculado { get; set; }
    }
}
