//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_Empleados_RRHH
    {
        public decimal Cod_Interno { get; set; }
        public decimal NoEmpleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Empleado { get; set; }
        public string No_Inss { get; set; }
        public string No_Cedula { get; set; }
        public string Estado { get; set; }
        public string IdArea { get; set; }
        public string Area { get; set; }
    }
}
