//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_TechosPresupuestarios
    {
        public string Anio { get; set; }
        public int IdArea { get; set; }
        public string CodigoArea { get; set; }
        public string NombreArea { get; set; }
        public int IdFuenteFinanciamiento { get; set; }
        public string NombreFuenteFinanciamiento { get; set; }
        public string SiglasFuenteFinanciamiento { get; set; }
        public decimal TechaAnual { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<byte> IdMes { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
