//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_PrestamoDocumentos
    {
        public int IdPrestamo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public Nullable<byte> TipoDocumento { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public Nullable<int> IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public string Solicitado { get; set; }
        public string Autorizado { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    }
}
