//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_Pagos_Matricula
    {
        public int IdPago { get; set; }
        public string EstudianteCarne { get; set; }
        public int IdImpresion { get; set; }
        public string SerieRecibo { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
