//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_AsientosProceso
    {
        public string IdComprobanteDiario { get; set; }
        public string IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
        public string TipoComprobante { get; set; }
        public string Estado { get; set; }
        public string Concepto { get; set; }
        public string Nombre { get; set; }
    }
}
