//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_RecibosPiensa
    {
        public int IdRecibo { get; set; }
        public int IdImpresion { get; set; }
        public string Recibimos { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string Descripcion { get; set; }
        public string Concepto { get; set; }
        public byte TipoMoneda { get; set; }
        public string Moneda { get; set; }
        public decimal Monto { get; set; }
        public bool RegAnulado { get; set; }
    }
}
