//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qry_SolicitudCompraDetalle
    {
        public string NumLicitacion { get; set; }
        public string Denominacion { get; set; }
        public int IdSolicitud { get; set; }
        public int CodReferencia { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public string FuenteFinanciamiento { get; set; }
        public int IdArea { get; set; }
        public string Area { get; set; }
        public Nullable<int> IdProductoBodega { get; set; }
        public Nullable<int> IdProductoSIPPSI { get; set; }
        public string strProducto { get; set; }
        public int IdUnidadMedida { get; set; }
        public string strUnidadMedida { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> Pedido { get; set; }
        public string DescripcionP { get; set; }
    }
}
