//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query_ContratosLicitacion_SISCOM
    {
        public string NumLicitacion { get; set; }
        public Nullable<int> NumPAC { get; set; }
        public Nullable<int> Año { get; set; }
        public int Clasificacion { get; set; }
        public string Denominacion { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string NombreProveedor { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string NombreContrato { get; set; }
        public Nullable<decimal> MontoAdendum { get; set; }
        public Nullable<System.DateTime> IniciaAdendum { get; set; }
        public Nullable<System.DateTime> FinAdendum { get; set; }
        public string TipoAdendum { get; set; }
    }
}
