//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query_GenerarCD
    {
        public string IdComprobanteDiario { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public byte IdPrograma { get; set; }
        public string IdImpresion { get; set; }
        public byte IdTipoComprobante { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
        public string Concepto { get; set; }
        public byte Estado { get; set; }
        public Nullable<byte> IdFuenteFinanciamiento { get; set; }
        public string Fuente { get; set; }
        public string TipoComprobante { get; set; }
        public string Ver { get; set; }
    }
}
