//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query_SolcitucCk_SIPPSI
    {
        public string IdSolicitudCheque { get; set; }
        public string Concepto { get; set; }
        public string TipoBeneficiario { get; set; }
        public string CodigoBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public int IDArea { get; set; }
        public string Area { get; set; }
        public Nullable<int> IdFuente { get; set; }
        public string Fuente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CodigoOG { get; set; }
        public string ObjetoGasto { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> IDAreaAG { get; set; }
        public string AreaAG { get; set; }
        public Nullable<decimal> MontoAAG { get; set; }
        public string Estado { get; set; }
    }
}
