//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboDetalle
    {
        public int IdRecibo { get; set; }
        public string SerieRecibo { get; set; }
        public byte IdPrograma { get; set; }
        public byte IdReciboDetalle { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public byte IdPago { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Recibo Recibo { get; set; }
    }
}
