//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.ArqueoNoEfectivo = new HashSet<ArqueoNoEfectivo>();
            this.ArqueoRecibo = new HashSet<ArqueoRecibo>();
            this.Asiento = new HashSet<Asiento>();
            this.ReciboDet = new HashSet<ReciboDet>();
            this.ReciboPago = new HashSet<ReciboPago>();
        }
    
        public int IdRecibo { get; set; }
        public string Serie { get; set; }
        public int IdDetAperturaCaja { get; set; }
        public byte IdFuenteFinanciamiento { get; set; }
        public string Recibimos { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdInfoRecibo { get; set; }
        public Nullable<int> IdOrdenPago { get; set; }
        public bool isRecibimosPorCuenta { get; set; }
        public string UsuarioCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoNoEfectivo> ArqueoNoEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoRecibo> ArqueoRecibo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual OrdenPago OrdenPago { get; set; }
        public virtual DetAperturaCaja DetAperturaCaja { get; set; }
        public virtual InfoRecibo InfoRecibo { get; set; }
        public virtual SerieRecibo SerieRecibo { get; set; }
        public virtual ReciboAnulado ReciboAnulado { get; set; }
        public virtual ReciboDatos ReciboDatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboDet> ReciboDet { get; set; }
        public virtual ReciboDiferencias ReciboDiferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboPago> ReciboPago { get; set; }
        public virtual ReciboSIRA ReciboSIRA { get; set; }
    }
}
