//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReciboPago()
        {
            this.ArqueoDocumento = new HashSet<ArqueoDocumento>();
            this.ArqueoNoEfectivo = new HashSet<ArqueoNoEfectivo>();
            this.RectificacionPago = new HashSet<RectificacionPago>();
            this.ReciboPago1 = new HashSet<ReciboPago>();
        }
    
        public int IdReciboPago { get; set; }
        public int IdRecibo { get; set; }
        public string Serie { get; set; }
        public int IdFormaPago { get; set; }
        public decimal Monto { get; set; }
        public int IdMoneda { get; set; }
        public Nullable<int> IdRectificacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public bool regAnulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoDocumento> ArqueoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoNoEfectivo> ArqueoNoEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RectificacionPago> RectificacionPago { get; set; }
        public virtual RectificacionPago RectificacionPago1 { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual Recibo Recibo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboPago> ReciboPago1 { get; set; }
        public virtual ReciboPago ReciboPago2 { get; set; }
        public virtual ReciboPagoBono ReciboPagoBono { get; set; }
        public virtual ReciboPagoDeposito ReciboPagoDeposito { get; set; }
        public virtual ReciboPagoTarjeta ReciboPagoTarjeta { get; set; }
        public virtual ReciboPagoCheque ReciboPagoCheque { get; set; }
    }
}
