//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboPagare
    {
        public int IdReciboPagare { get; set; }
        public int IdRecibo { get; set; }
        public string SerieRecibo { get; set; }
        public byte IdPrograma { get; set; }
        public string Numero { get; set; }
        public string Deudor { get; set; }
        public string Autorizacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public byte Tipo { get; set; }
        public byte TipoMoneda { get; set; }
        public decimal Monto { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual Recibo Recibo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
