//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudEstado
    {
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public byte IdSolicitudEstado { get; set; }
        public byte IdEstado { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public bool Impreso { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
    
        public virtual SolicitudCheque SolicitudCheque { get; set; }
    }
}
