//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpContratoMovimientos
    {
        public string RUC { get; set; }
        public string Proveedor { get; set; }
        public string RazonSocial { get; set; }
        public string NombreContrato { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoAdendum { get; set; }
        public Nullable<System.DateTime> FechaAprobado { get; set; }
        public string Area { get; set; }
        public string Concepto { get; set; }
        public Nullable<byte> IdFuenteFinanciamiento { get; set; }
        public string DescripcionFuente { get; set; }
        public string IdSolicitudCheque { get; set; }
        public Nullable<decimal> MontoCk { get; set; }
        public Nullable<int> IdSolCk { get; set; }
        public string IdYear { get; set; }
        public Nullable<int> IdCheque { get; set; }
        public Nullable<int> NumeroCheque { get; set; }
        public string LoginCreacion { get; set; }
    }
}
