//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpConceptoCuenta
    {
        public string Carnet { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> IdPago { get; set; }
        public string PLCodigo { get; set; }
        public string FacultadCodigo { get; set; }
        public byte IdConcepto { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<byte> Moneda { get; set; }
        public string MonedaNombre { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<byte> RegAnulado { get; set; }
    }
}
