//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpConciliarRenglones_b1
    {
        public int Secuencia { get; set; }
        public byte Origen { get; set; }
        public Nullable<byte> TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<int> Codigo_P { get; set; }
        public Nullable<int> Interno_P { get; set; }
        public Nullable<int> Codigo_C { get; set; }
        public Nullable<int> Interno_C { get; set; }
        public Nullable<int> IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<byte> IdFuente { get; set; }
        public string Fuente { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public string CodigoCuenta { get; set; }
        public string CuentaBanco { get; set; }
        public Nullable<int> IdCuentaSuperior { get; set; }
        public string CodigoCuentaSuperior { get; set; }
        public string CuentaSuperior { get; set; }
        public Nullable<byte> IdMes { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<decimal> Contabilidad { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public string Conciliada { get; set; }
        public Nullable<byte> Nivel { get; set; }
        public string LoginCreacion { get; set; }
    }
}
