//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpComprobantePrint
    {
        public int IdComprobante { get; set; }
        public byte TipoComprobante { get; set; }
        public byte IdPrograma { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public string IdInterfaz { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> ParcialCordoba { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public decimal TotalDebe { get; set; }
        public decimal TotalHaber { get; set; }
        public string LoginImpresion { get; set; }
    }
}
