//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpCuentaContable1
    {
        public Nullable<bool> Seleccionar { get; set; }
        public int IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public byte Evento { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<byte> IdRecinto { get; set; }
        public Nullable<byte> IdDocumentoBodega { get; set; }
    }
}
