//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpConceptoFacultad
    {
        public short IdConcepto { get; set; }
        public byte IdActividad { get; set; }
        public string IdFacultad { get; set; }
        public string LoginCreacion { get; set; }
        public bool Estado { get; set; }
        public string Nombre { get; set; }
    }
}
