//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpCuentaContableEstructura
    {
        public int Secuencia { get; set; }
        public Nullable<byte> Nivel { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public string CuentaSuperior { get; set; }
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public Nullable<bool> Acumulativa { get; set; }
        public string LoginCreacion { get; set; }
    }
}
