//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpConciliacionBancoDetalle
    {
        public short IdConciliacionBanco { get; set; }
        public byte TipoDocumento { get; set; }
        public int IdDocumento { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public Nullable<byte> Tipo { get; set; }
        public Nullable<int> IdDocumentoImpresion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> SaldoTCSolicitud { get; set; }
        public Nullable<decimal> SaldoTCFechaImpresion { get; set; }
        public bool ComprobanteFlotante { get; set; }
        public string LoginCreacion { get; set; }
        public bool Estado { get; set; }
        public decimal SaldoLibroBanco { get; set; }
        public decimal SaldoBanco { get; set; }
        public decimal SaldoDolar { get; set; }
        public bool Ajuste { get; set; }
    }
}
