//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpConciliarRenglones
    {
        public Nullable<byte> Origen { get; set; }
        public Nullable<byte> TipoDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<int> Interno { get; set; }
        public Nullable<int> IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<byte> IdFuente { get; set; }
        public string Fuente { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public string CodigoCuenta { get; set; }
        public string CuentaBanco { get; set; }
        public Nullable<int> IdCuentaSuperior { get; set; }
        public string CuentaSuperior { get; set; }
        public Nullable<byte> TipoMoneda { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Conciliada { get; set; }
        public string LoginCreacion { get; set; }
    }
}
