//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpComprobanteRendir
    {
        public int Interno { get; set; }
        public Nullable<int> IdImpresion { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<int> Interno_ck { get; set; }
        public Nullable<int> Cheque { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public string Año_ck { get; set; }
        public Nullable<byte> Vinculado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginCreacion { get; set; }
    }
}
