//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpContrato_EstadoCuenta
    {
        public int Secuencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RUC { get; set; }
        public string NombreContrato { get; set; }
        public string Proveedor { get; set; }
        public string RazonSocial { get; set; }
        public string Area { get; set; }
        public string Concepto { get; set; }
        public Nullable<byte> IdFuenteFinanciamiento { get; set; }
        public string DescripcionFuente { get; set; }
        public Nullable<byte> IdDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<int> IdSolicitudCheque { get; set; }
        public Nullable<int> IdSolcCk { get; set; }
        public string IdYear { get; set; }
        public Nullable<int> IdCheque { get; set; }
        public Nullable<int> NumeroCheque { get; set; }
        public Nullable<byte> IdEstado { get; set; }
        public string NombreEstado { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string LoginCreacion { get; set; }
    }
}
