//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpLineaComprobante
    {
        public int IdAsiento { get; set; }
        public int IdComprobante { get; set; }
        public byte TipoComprobante { get; set; }
        public string LoginCreacion { get; set; }
        public byte IdPrograma { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public Nullable<int> IdAuxiliar { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public int IdGrupo { get; set; }
        public short IdOrden { get; set; }
        public string IdInterfaz { get; set; }
        public string Descripcion { get; set; }
        public bool Agrupa { get; set; }
        public Nullable<bool> DebeHaber { get; set; }
        public Nullable<decimal> ParcialCordoba { get; set; }
        public Nullable<decimal> ParcialDolar { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public byte Estado { get; set; }
        public bool Transferible { get; set; }
    }
}
