//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpMontoEgresoFuente
    {
        public int IdOrden { get; set; }
        public short IdCuentaContable { get; set; }
        public string CuentaSuperior { get; set; }
        public string DescripcionS { get; set; }
        public string CuentaContable { get; set; }
        public string Descripcion { get; set; }
        public decimal Aporte { get; set; }
        public decimal Inversiones { get; set; }
        public decimal Ingresos { get; set; }
        public Nullable<decimal> Cooperacion { get; set; }
        public Nullable<decimal> Lanamet { get; set; }
        public decimal FondosG { get; set; }
        public decimal DBE { get; set; }
        public string LoginCreacion { get; set; }
        public int IdPeriodoEspecifico { get; set; }
    }
}
