//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpPerfilContenido
    {
        public byte IdPerfil { get; set; }
        public int IdMenu { get; set; }
        public int NoItem { get; set; }
        public int NoFuncion { get; set; }
        public string LoginCreacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Comando { get; set; }
        public bool Visualizar { get; set; }
        public bool Crear { get; set; }
        public bool Editar { get; set; }
        public bool Eliminar { get; set; }
        public bool Imprimir { get; set; }
        public bool Ejecutar { get; set; }
        public bool Estado { get; set; }
        public bool Diferenciado { get; set; }
    }
}
