//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpProveedorContrato
    {
        public bool Seleccionar { get; set; }
        public string RUC { get; set; }
        public string NombreContrato { get; set; }
        public string Proveedor { get; set; }
        public string LoginCreacion { get; set; }
    }
}
