//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpReciboFlujoEfectivo
    {
        public int IdRecibo { get; set; }
        public byte Tipo { get; set; }
        public string SerieRecibo { get; set; }
        public byte IdPrograma { get; set; }
        public decimal Denominacion { get; set; }
        public string LoginCreacion { get; set; }
        public short CantidadCordoba { get; set; }
        public decimal MontoCordoba { get; set; }
        public short CantidadDolar { get; set; }
        public decimal MontoDolar { get; set; }
        public bool Estado { get; set; }
    }
}
