//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpSolicitudesArchivo
    {
        public int IdSolicitudCheque { get; set; }
        public int NoCheque { get; set; }
        public int IdYear { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Beneficiario { get; set; }
        public string Concepto { get; set; }
        public string AreaSolicitante { get; set; }
        public string Fuente { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Monto_C { get; set; }
        public Nullable<decimal> Monto_D { get; set; }
        public bool Imprimir { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginCreacion { get; set; }
    }
}
