//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpSolicitudTesoreria
    {
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public byte Tipo { get; set; }
        public Nullable<int> IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NombreActividad { get; set; }
        public string NombreBeneficiario { get; set; }
        public string Monto { get; set; }
        public string Concepto { get; set; }
        public bool Estado { get; set; }
        public string LoginCreacion { get; set; }
    }
}
