//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionesServicio
    {
        public int IdTransaccion { get; set; }
        public Nullable<byte> IdTipoTransaccionBank { get; set; }
        public Nullable<byte> idBanco { get; set; }
        public string Sucursal { get; set; }
        public string Cajero { get; set; }
        public string DetalleTransaccion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool IsError { get; set; }
    
        public virtual TipoTransaccionBank TipoTransaccionBank { get; set; }
        public virtual Banco Banco { get; set; }
    }
}
