//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia_Area_D
    {
        public int IdTransferencia { get; set; }
        public int Periodo { get; set; }
        public Nullable<byte> IdFuente { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<byte> IdMoneda { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<byte> Estado { get; set; }
        public Nullable<int> IdImpresion { get; set; }
        public string strConcepto { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginImpresion { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public string LoginModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    }
}
