//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_reciboPagos
    {
        public int IdRecibo { get; set; }
        public string Serie { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdFormaPago { get; set; }
        public string FormaPago { get; set; }
        public Nullable<decimal> MN_LMonto { get; set; }
        public Nullable<decimal> ME_LMonto { get; set; }
    }
}
