//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoucherBanco()
        {
            this.ReciboPagoTarjeta = new HashSet<ReciboPagoTarjeta>();
        }
    
        public int IdVoucherBanco { get; set; }
        public int IdDetApertura { get; set; }
        public string Autorizacion { get; set; }
        public string Referencia { get; set; }
        public string Factura { get; set; }
        public string Stan { get; set; }
        public string Tarjeta { get; set; }
        public int IdMoneda { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string StanAnulado { get; set; }
        public Nullable<System.DateTime> FechaAnulado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual DetAperturaCaja DetAperturaCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboPagoTarjeta> ReciboPagoTarjeta { get; set; }
    }
}
