//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AreaEquivalencia
    {
        public string CodRH { get; set; }
        public string DescripcionRH { get; set; }
        public string EstadoRH { get; set; }
        public byte IdF { get; set; }
        public string DescripcionF { get; set; }
        public byte EstadoF { get; set; }
        public string IdInterfaz { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
