//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Aranceles
    {
        public int IdArancel { get; set; }
        public string Arancel { get; set; }
        public int IdTipo { get; set; }
        public string Tipo { get; set; }
        public int IdArancelPrecio { get; set; }
        public decimal Precio { get; set; }
        public int IdMoneda { get; set; }
        public string Moneda { get; set; }
        public string IdArea { get; set; }
        public string Area { get; set; }
    }
}
