//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Areas
    {
        public string codigo { get; set; }
        public string cod_padre { get; set; }
        public string tipo_area { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string nombre { get; set; }
        public string strtipo_area { get; set; }
    }
}
