//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AgenteExterno
    {
        public int IdAgenteExterno { get; set; }
        public Nullable<int> PersonaCodigo { get; set; }
        public Nullable<byte> IdMunicipio { get; set; }
        public string AgenteExterno { get; set; }
        public string RUC { get; set; }
        public string Cedula { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SitioWeb { get; set; }
        public bool RegAnulado { get; set; }
    }
}
