//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Beneficiario
    {
        public int IdBeneficiario { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdEmpleado_RRHH { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string INSS { get; set; }
        public string Ubicacion { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Proveedor { get; set; }
        public string RUC { get; set; }
        public Nullable<int> PersonaCodigo { get; set; }
        public string PersonaNombre { get; set; }
        public string PersonaCedula { get; set; }
        public Nullable<bool> RegAnulado { get; set; }
    }
}
