//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultarRecibos
    {
        public string SerieRecibo { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Annio { get; set; }
        public string IdImpresion { get; set; }
        public string Recibimos { get; set; }
        public string Concepto { get; set; }
        public string NombreCuenta { get; set; }
        public string Estudiante { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> MontoDetalle { get; set; }
        public Nullable<decimal> EfectivoCordobas { get; set; }
        public Nullable<decimal> EfectivoDolares { get; set; }
        public Nullable<decimal> ChequeCordobas { get; set; }
        public Nullable<decimal> ChequeDolares { get; set; }
        public Nullable<decimal> TarjetaCordobas { get; set; }
        public Nullable<decimal> TarjetaDolares { get; set; }
        public Nullable<decimal> PagareCordobas { get; set; }
        public Nullable<decimal> PagareDolares { get; set; }
        public Nullable<decimal> BonoCordobas { get; set; }
        public Nullable<decimal> BonoDolares { get; set; }
        public string NombreCandidato { get; set; }
        public string NombreEmpleado { get; set; }
        public string Proveedor { get; set; }
        public string AgenteExterno { get; set; }
        public string Estado { get; set; }
        public string Recinto { get; set; }
        public string IdRecinto { get; set; }
        public string NombreUsuario { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public string NombreActividad { get; set; }
        public byte IdActividad { get; set; }
        public byte IdProyecto { get; set; }
    }
}
