//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EstadoCuenta
    {
        public System.DateTime Fecha { get; set; }
        public string Documento { get; set; }
        public string Concepto { get; set; }
        public int IdComprobante { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public bool DebeHaber { get; set; }
        public Nullable<decimal> ParcialCordoba { get; set; }
    }
}
