//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Empleado_EdoCuenta
    {
        public Nullable<int> IdEmpleado { get; set; }
        public string Cuenta { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int IdEstadoCuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Documento { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public decimal Saldo { get; set; }
        public string LoginImpresion { get; set; }
    }
}
