//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Estructura_Jerarquia
    {
        public byte Id { get; set; }
        public string IdInterfaz { get; set; }
        public string Descripcion { get; set; }
        public int IdGrupo { get; set; }
        public string Nivel { get; set; }
    }
}
