//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Empleado
    {
        public int IdEmpleado { get; set; }
        public Nullable<int> IdEmpleado_RRHH { get; set; }
        public Nullable<int> PersonaCodigo { get; set; }
        public string Cedula { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string INSS { get; set; }
        public string Ubicacion { get; set; }
        public string Cargo { get; set; }
        public string Extension { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string Descripcion { get; set; }
        public decimal Saldo { get; set; }
        public bool RegAnulado { get; set; }
        public Nullable<int> Empleado { get; set; }
        public string NombreEmpleado { get; set; }
        public Nullable<short> IdCuentaContableAnticipo { get; set; }
        public decimal SaldoAnticipo { get; set; }
        public string NombreAnticipo { get; set; }
    }
}
