//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Facultad
    {
        public string IdFacultad { get; set; }
        public Nullable<short> IdRecinto { get; set; }
        public string Nombre { get; set; }
        public string Siglas { get; set; }
        public bool RegAnulado { get; set; }
    }
}
