//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GeneraSolicitudes
    {
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public int NumCheque { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public Nullable<byte> IdActividad { get; set; }
        public string Area { get; set; }
        public int IdBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<byte> TipoMoneda { get; set; }
        public string Moneda { get; set; }
        public decimal TasaCambio { get; set; }
        public decimal Cantidad { get; set; }
        public string Concepto { get; set; }
        public byte IdEstado { get; set; }
        public string Estado { get; set; }
        public Nullable<byte> IdFuente { get; set; }
        public string Fuente { get; set; }
        public Nullable<int> IdSolicitudCheque_SIPPSI { get; set; }
    }
}
