//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Persona
    {
        public int PersonaCodigo { get; set; }
        public string PersonaNombre { get; set; }
        public byte RegAnulado { get; set; }
        public string PersonaCedula { get; set; }
        public Nullable<int> Persona { get; set; }
    }
}
