//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Prematricula
    {
        public string IdPrematricula { get; set; }
        public string AñoLectivo { get; set; }
        public int Carnet { get; set; }
        public string Nombre { get; set; }
        public byte ESTipo { get; set; }
        public string PrimeraOpcion { get; set; }
        public string SegundaOpcion { get; set; }
        public Nullable<bool> isBecado { get; set; }
    }
}
