//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Recibo
    {
        public int IdRecibo { get; set; }
        public string SerieRecibo { get; set; }
        public byte IdPrograma { get; set; }
        public byte IdRecinto { get; set; }
        public string Recinto { get; set; }
        public string Siglas { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public int IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte TipoMoneda { get; set; }
        public decimal TasaCambio { get; set; }
        public byte IdActividad { get; set; }
        public byte IdProyecto { get; set; }
        public byte IdProgramaRegistro { get; set; }
        public string NombreActividad { get; set; }
        public string NombreProyecto { get; set; }
        public string NombrePrograma { get; set; }
        public Nullable<int> IdPrematricula { get; set; }
        public string ALCodigo { get; set; }
        public string NombreCandidato { get; set; }
        public string EstudianteCarne { get; set; }
        public string Estudiante { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> IdAgenteExterno { get; set; }
        public string AgenteExterno { get; set; }
        public string Recibimos { get; set; }
        public string CuentaContable { get; set; }
        public bool Efectivo { get; set; }
        public bool Cheque { get; set; }
        public bool TarjetaCredito { get; set; }
        public bool Pagare { get; set; }
        public bool Bono { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string MontoLetra { get; set; }
        public byte IdFuenteFinanciamiento { get; set; }
        public string NombreFuente { get; set; }
        public string LoginCreacion { get; set; }
        public string Numero { get; set; }
        public string NombreBanco { get; set; }
        public string SiglasBanco { get; set; }
        public string NombreUsuario { get; set; }
        public string FormaPago { get; set; }
        public string Cuenta { get; set; }
        public bool RegAnulado { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> MontoDetalle { get; set; }
        public string NombreCuenta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> IdConcepto { get; set; }
    }
}
