//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Recibo_FormasPago
    {
        public int IdRecibo { get; set; }
        public string SerieRecibo { get; set; }
        public byte IdPrograma { get; set; }
        public string Programa { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
        public int IdImpresion { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte MonedaRecibo { get; set; }
        public decimal TasaCambio { get; set; }
        public byte IdActividad { get; set; }
        public string Actividad { get; set; }
        public string EstudianteCarne { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdAgenteExterno { get; set; }
        public string Recibimos { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string Concepto { get; set; }
        public string Descripcion { get; set; }
        public bool Efectivo { get; set; }
        public decimal MontoRecibo { get; set; }
        public bool Bono { get; set; }
        public bool Pagare { get; set; }
        public bool TarjetaCredito { get; set; }
        public bool Cheque { get; set; }
        public Nullable<int> IdReciboBono { get; set; }
        public Nullable<byte> MonedaBono { get; set; }
        public Nullable<decimal> MontoBono { get; set; }
        public Nullable<int> IdReciboCheque { get; set; }
        public Nullable<byte> MonedaCheque { get; set; }
        public Nullable<decimal> MontoCheque { get; set; }
        public Nullable<byte> Tipo { get; set; }
        public Nullable<decimal> Denominacion { get; set; }
        public Nullable<short> CantidadCordoba { get; set; }
        public Nullable<short> CantidadDolar { get; set; }
        public Nullable<int> IdReciboPagare { get; set; }
        public Nullable<byte> MonedaPagare { get; set; }
        public Nullable<decimal> MontoPagare { get; set; }
        public Nullable<int> IdReciboTarjeta { get; set; }
        public Nullable<byte> MonedaTarjeta { get; set; }
        public Nullable<decimal> MontoTarjeta { get; set; }
        public byte IdFuenteFinanciamiento { get; set; }
        public string NombreFuente { get; set; }
        public byte IdProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public bool RegAnulado { get; set; }
        public byte IdRecinto { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<short> IdConcepto { get; set; }
        public string NombreCuenta { get; set; }
    }
}
