//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RendicionCuenta
    {
        public int IdRendicion { get; set; }
        public string IdYear { get; set; }
        public int NumCheque { get; set; }
        public Nullable<int> IdSolCk { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaRendicion { get; set; }
        public string NombreBeneficiario { get; set; }
        public string Concepto { get; set; }
        public string Observaciones { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<byte> TipoMoneda { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Aritmetico { get; set; }
        public string Manchones { get; set; }
        public string Soportes { get; set; }
        public string Conceptos { get; set; }
        public string Beneficiarios { get; set; }
        public string Autorizado { get; set; }
        public string Desglose { get; set; }
        public string Justificacion { get; set; }
        public string OInconsistencias { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string LoginCreacion { get; set; }
        public Nullable<byte> RegAnulado { get; set; }
        public string Moneda { get; set; }
        public string Simbolo { get; set; }
    }
}
