//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReciboReporte
    {
        public int IdRecibo { get; set; }
        public string SerieRecibo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdImpresion { get; set; }
        public string Recibimos { get; set; }
        public Nullable<decimal> EfectivoCordobas { get; set; }
        public Nullable<decimal> EfectivoDolares { get; set; }
        public decimal ChequeCordobas { get; set; }
        public decimal ChequeDolares { get; set; }
        public decimal TarjetaCordobas { get; set; }
        public decimal TarjetaDolares { get; set; }
        public decimal PagareCordobas { get; set; }
        public decimal PagareDolares { get; set; }
        public decimal BonoCordobas { get; set; }
        public decimal BonoDolares { get; set; }
        public string Estudiante { get; set; }
        public string NombreEmpleado { get; set; }
        public string Proveedor { get; set; }
        public string AgenteExterno { get; set; }
        public bool RegAnulado { get; set; }
        public string Recinto { get; set; }
        public Nullable<decimal> MontoRecibo { get; set; }
        public byte TipoMoneda { get; set; }
        public string Moneda { get; set; }
        public byte IdRecinto { get; set; }
        public byte IdActividad { get; set; }
        public string NombreActividad { get; set; }
        public byte IdFuenteFinanciamiento { get; set; }
        public string NombreFuente { get; set; }
        public string LoginCreacion { get; set; }
        public string NombreUsuario { get; set; }
        public byte IdPrograma { get; set; }
        public string NombrePrograma { get; set; }
        public string NombreProyecto { get; set; }
        public bool Efectivo { get; set; }
        public bool Cheque { get; set; }
        public bool TarjetaCredito { get; set; }
        public bool Pagare { get; set; }
        public bool Bono { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> MontoDetalle { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string NombreCuenta { get; set; }
        public string Descripcion { get; set; }
        public byte IdProyecto { get; set; }
        public string NombreCandidato { get; set; }
        public byte IdPeriodoEspecifico { get; set; }
    }
}
