//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SolicitudCheque
    {
        public int IdSolicitudCheque { get; set; }
        public string IdYear { get; set; }
        public byte IdPrograma { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> IdActividad { get; set; }
        public int IdBeneficiario { get; set; }
        public Nullable<byte> IdPeriodoEspecifico { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<byte> TipoMoneda { get; set; }
        public decimal TasaCambio { get; set; }
        public decimal Cantidad { get; set; }
        public string Concepto { get; set; }
        public bool Presupuesto { get; set; }
        public string NombreEstado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
        public Nullable<short> IdCuentaContable { get; set; }
        public string CuentaContable { get; set; }
        public string Cuenta { get; set; }
        public string Fuente { get; set; }
        public Nullable<byte> IdFuenteFinanciamiento { get; set; }
        public string NombreBeneficiario { get; set; }
        public string NombreActividad { get; set; }
        public Nullable<int> IdImpresion { get; set; }
        public byte Estado { get; set; }
        public byte IdProyecto { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
        public int Actividad { get; set; }
        public System.DateTime FechaE { get; set; }
        public string DiaE { get; set; }
        public string MesE { get; set; }
        public string AnioE { get; set; }
        public Nullable<int> IdSolicitudCheque_SIPPSI { get; set; }
        public bool Impreso { get; set; }
        public Nullable<int> IdComprobantePago { get; set; }
    }
}
