//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vws_CatalogoContable
    {
        public short IdCuentaContable { get; set; }
        public Nullable<int> IdOrden { get; set; }
        public Nullable<byte> IdOrdenGrupo { get; set; }
        public Nullable<byte> IdTipoCuenta { get; set; }
        public string CuentaSuperior { get; set; }
        public Nullable<int> CuentaGrupo { get; set; }
        public string CuentaContable { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public bool Tipo { get; set; }
        public bool BalanceResultado { get; set; }
        public bool Acumulativa { get; set; }
        public string Instructivo { get; set; }
        public string InstructivoDebito { get; set; }
        public string InstructivoCredito { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public string LoginCreacion { get; set; }
        public bool RegAnulado { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string Codigo { get; set; }
    }
}
